COMMENT: 'Using our framework to implement LED2-Net, Training on ZInd'
TAG: 'zind'
SEED: 123
MODEL:
  NAME: 'LGT_Net'
  ARGS: [ {
    'decoder_name': 'LSTM',
    'output_name': 'LED',
    'dropout': 0.5,
  } ]
TRAIN:
  DEVICE: 'cuda:0'
  SCRATCH: False
  DETERMINISTIC: True
  CRITERION:
    DEPTH:
      WEIGHT: 1.0
      LOSS: 'LEDLoss'
      NEED_ALL: True
  BASE_LR:
    3e-4
  EPOCHS: 200
  RESUME_LAST: False
  OPTIMIZER:
    NAME: 'adam'
DATA:
  DATASET: 'zind'
  DIR: 'src/dataset/zind'
  BATCH_SIZE: 6
  NUM_WORKERS: 6
  FOR_TEST_INDEX: None
  AUG:
    FLIP: True
    STRETCH: True
    ROTATE: True
    GAMMA: True
AMP_OPT_LEVEL: 'O0'